databases/models/item.py
from sqlalchemy import Integer, String, ForeignKey, Date, Enum, Boolean
from sqlalchemy.orm import relationship, Mapped, mapped_column
from datetime import date
import enum
from ..base import db

class StatusEnum(enum.Enum):
    Active = 1
    DroppedOff = 2
    InRepair = 3
    Recycled = 4
    Donated = 5

    def __str__(self):
        return str(self.name)

class Item(db.Model):
    __tablename__ = 'Item'

    itemID: Mapped[int] = mapped_column(Integer, primary_key = True, autoincrement = True, nullable = False, unique = True)
    vendorID: Mapped[int] = mapped_column(Integer, ForeignKey('Vendor.vendorID'))
    userID: Mapped[int] = mapped_column(Integer, ForeignKey('User.userID' ))
    itemCategoryID: Mapped[int] = mapped_column(Integer, ForeignKey('ItemCategory.itemCategoryID'))
    expiryDate: Mapped[date] = mapped_column(Date, nullable = False)
    status: Mapped[StatusEnum] = mapped_column(Enum(StatusEnum))
    userNotes: Mapped[str] = mapped_column(String(50), nullable = True)
    isDeleted: Mapped[bool] = mapped_column(Boolean, default=False,  nullable=True)
    
    #Relationships back to User, Vendor, and ItemCategory
    user = relationship("User", back_populates = "items", passive_deletes=True)
    vendor = relationship("Vendor", back_populates = "items", passive_deletes=True)
    itemCategory = relationship("ItemCategory", back_populates = "items", passive_deletes=True)

    def __int__(self):
        return self.itemID

databases/models/itemCategory.py
from sqlalchemy import Integer, String, Boolean
from sqlalchemy.orm import relationship, Mapped, mapped_column
from ..base import db


class ItemCategory(db.Model):
    __tablename__ = 'ItemCategory'

    itemCategoryID: Mapped[int] = mapped_column(Integer, primary_key = True, autoincrement = True, nullable = False, unique = True)
    itemCategoryName:  Mapped[str] = mapped_column(String(50), nullable = False, unique=True)
    isDeleted: Mapped[bool] = mapped_column(Boolean, default=False,  nullable=True)

    #one to many relationship with item
    items = relationship("Item", back_populates="itemCategory")
    
    def __str__(self):
        return str(self.itemCategoryName)
    
    def get_id(self):
        return str(self.itemCategoryID)
   

databases/models/user.py
from sqlalchemy import Integer, String, Enum, Boolean, LargeBinary
from sqlalchemy.orm import relationship, Mapped, mapped_column
from ..base import db
import enum
from flask_login import UserMixin

class AccessRoleEnum(enum.Enum):
    User = 1
    Admin = 2

    def __str__(self):
        return str(self.name)


class User(UserMixin, db.Model):
    __tablename__ = 'User'

    userID: Mapped[int] = mapped_column(Integer, primary_key = True, autoincrement = True, nullable = False, unique = True)
    firstName: Mapped[str] = mapped_column(String (50), nullable = False)
    lastName: Mapped[str] = mapped_column(String (50), nullable = False)
    username: Mapped[str] = mapped_column(String (25), unique = True, nullable = False)
    password: Mapped[bytes] = mapped_column(LargeBinary(60), nullable = False)
    accessRole:  Mapped[AccessRoleEnum] = mapped_column(Enum(AccessRoleEnum))
    isDeleted: Mapped[bool] = mapped_column(Boolean, default=False,  nullable=True) 

    #Defining one to many relationship with Item
    items = relationship("Item", back_populates="user")
   
    def __str__(self):
        return str(self.userID) + f" ({str(self.firstName)} {str(self.lastName)})"
    
    def get_id(self):
        return str(self.userID)

databases/models/vendor.py
from sqlalchemy import Integer, String, Boolean
from sqlalchemy.orm import relationship, Mapped, mapped_column
from ..base import db

class Vendor(db.Model):
    __tablename__ = 'Vendor'

    vendorID: Mapped[int] = mapped_column(Integer, primary_key = True, autoincrement = True, nullable = False, unique = True)
    vendorName: Mapped[str] = mapped_column(String(50), nullable = False)
    sustainabilityCertified: Mapped[bool] = mapped_column(Boolean, nullable = False)
    isDeleted: Mapped[bool] = mapped_column(Boolean, default=False,  nullable=True)

    #one to many relationship with item
    items = relationship("Item", back_populates = "vendor")

    def __str__(self):
        return str(self.vendorName)
    
    def get_id(self):
        return str(self.vendorID)

forms/loginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField ,SubmitField
from wtforms.validators import InputRequired, length



class loginForm(FlaskForm):
    username = StringField('username', validators=[InputRequired('username required'), length(min=5, max=50, message='Username must be in 5 to 50 characters')])
    password = PasswordField('Password',validators=[InputRequired('Password required'), length(min=8)])
    submit = SubmitField('Login')

routes/itemCategoryRoutes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
import databases.models as models
from databases.models.user import AccessRoleEnum
from databases.base import db
from forms import createItemCategoryForm

#Blueprints to define all routes linking to item category CRUD functions
itemCategory_bp = Blueprint('itemCategory', __name__)

@itemCategory_bp.route("/categories")
@login_required
def listCategories():
    itemCategories = models.ItemCategory.query.filter_by(isDeleted=False)
    deletedCategories = models.ItemCategory.query.filter_by(isDeleted=True).all()
    return render_template('itemCategory.html', itemCategories=itemCategories, deletedCategories=deletedCategories, AccessRoleEnum=AccessRoleEnum)

@itemCategory_bp.route("/categories/create", methods=['GET', 'POST'])
@login_required
def addItemCategory():
    form = createItemCategoryForm()
    if form.validate_on_submit():
        try:
            formInput = models.ItemCategory(itemCategoryName=form.itemCategoryName.data)
            db.session.add(formInput)
            db.session.commit()
            flash(f"Item category created successfully!", "success")
        except: 
            db.session.rollback()
            flash(f"Something went wrong. Please try again.", "danger")
    return render_template("addItemCategory.html", form=form)

@itemCategory_bp.route("/categories/update/<int:itemCategoryID>", methods=['GET', 'POST'])
@login_required
def updateCategory(itemCategoryID):
    category= db.session.get(models.ItemCategory, itemCategoryID)
    if category.isDeleted:
        flash(f"Item category is deleted", "warning")
        return redirect(url_for('itemCategory.listCategories'))
    form = createItemCategoryForm(obj=category)
    if form.validate_on_submit():
        try:
            category.itemCategoryName = form.itemCategoryName.data
            db.session.commit()
            flash(f"Item category updated successfully!", "success")
        except:
            db.session.rollback()
            flash(f"Something went wrong. Please try again.", "danger")
    return render_template("addItemCategory.html", form=form)

@itemCategory_bp.route("/categories/delete/<int:itemCategoryID>", methods=['GET', 'POST'])
@login_required
def deleteCategory(itemCategoryID):

    #forbid User roles from deleting
    if current_user.accessRole == AccessRoleEnum.User:
        flash(f"Access denied! You do not have permission to delete item categories", "danger")
        return redirect(url_for('itemCategory.listCategories'))

    category= db.session.get(models.ItemCategory, itemCategoryID)
    if category.isDeleted:
        flash(f"Item category already deleted", "warning")
        return redirect(url_for('itemCategory.listCategories'))
    category.isDeleted = True
    db.session.commit()
    flash(f"Item category deleted successfully!", "success")
    return redirect(url_for('itemCategory.listCategories'))

@itemCategory_bp.route("/categories/restore/<int:itemCategoryID>", methods=['GET'])
@login_required
def restoreCategory(itemCategoryID):
   #forbid User roles from restoring
    if current_user.accessRole == AccessRoleEnum.User:
        flash(f"Access denied! You do not have permission to restore item categories", "danger")
        return redirect(url_for('itemCategory.listCategories'))
    category= db.session.get(models.ItemCategory, itemCategoryID)
    if category.isDeleted:
        category.isDeleted = False
        db.session.commit()
        flash(f"Item category restored successfully!", "success")
    return redirect(url_for('itemCategory.listCategories'))

routes/itemRoutes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
import databases.models as models
from databases.models.user import AccessRoleEnum
from databases.base import db
from forms import createItemForm

#Blueprints to define all routes linking to item CRUD functions
item_bp = Blueprint('item', __name__)

@item_bp.route("/items")
@login_required
def listItems():
    items =  (
        db.session.query(
            models.Item.itemID,
            models.Vendor.vendorName,
            models.User.username, 
            models.ItemCategory.itemCategoryName, 
            models.Item.expiryDate, 
            models.Item.status, 
            models.Item.userNotes
            )
            .join(models.Vendor, models.Item.vendorID == models.Vendor.vendorID)
            .join(models.User, models.Item.userID == models.User.userID)
            .join(models.ItemCategory, models.Item.itemCategoryID == models.ItemCategory.itemCategoryID)
            .filter_by(isDeleted=False)
    )

    deletedItems =  (
        db.session.query(
            models.Item.itemID,
            models.Vendor.vendorName,
            models.User.username, 
            models.ItemCategory.itemCategoryName, 
            models.Item.expiryDate, 
            models.Item.status, 
            models.Item.userNotes
        )
            .join(models.Vendor, models.Item.vendorID == models.Vendor.vendorID)
            .join(models.User, models.Item.userID == models.User.userID)
            .join(models.ItemCategory, models.Item.itemCategoryID == models.ItemCategory.itemCategoryID)
            .filter(models.Item.isDeleted == True).all()
    )
    
    return render_template('item.html', items=items, deletedItems=deletedItems, AccessRoleEnum=AccessRoleEnum)

@item_bp.route("/items/create", methods=['GET', 'POST'])
@login_required
def addItem():
    form = createItemForm()
    if form.validate_on_submit():
        try:
            print(f"vendorID: {form.vendorID.data}")
            formInput = models.Item(vendorID=form.vendorID.data.vendorID, userID=form.userID.data.userID, itemCategoryID=form.itemCategoryID.data.itemCategoryID, expiryDate=form.expiryDate.data, status=form.status.data, userNotes=form.userNotes.data )
            db.session.add(formInput)
            db.session.commit()
            flash(f"Item created successfully!", "success")
        except: 
            db.session.rollback()
            flash(f"Something went wrong. Please try again.", "danger")
    return render_template("addItem.html", form=form)

@item_bp.route("/items/update/<int:itemID>", methods=['GET', 'POST'])
@login_required
def updateItem(itemID):
     item= db.session.get(models.Item, itemID)
     if item.isDeleted:
         flash(f"Item is deleted", "warning")
         return redirect(url_for('item.listItems'))
     form = createItemForm(obj=item)
     if form.validate_on_submit():
        try:
            item.vendorID=form.vendorID.data.vendorID
            item.userID=form.userID.data.userID
            item.itemCategoryID=form.itemCategoryID.data.itemCategoryID
            item.expiryDate=form.expiryDate.data
            item.status=form.status.data
            item.userNotes=form.userNotes.data
            db.session.commit()
            flash(f"Item updated successfully!", "success")
        except:
            db.session.rollback()
            flash(f"Something went wrong. Please try again.", "danger")
     return render_template("addItem.html", form=form)

@item_bp.route("/items/delete/<int:itemID>", methods=['GET', 'POST'])
@login_required
def deleteItem(itemID):

    #forbid User roles from deleting
    if current_user.accessRole == AccessRoleEnum.User:
        flash(f"Access denied! You do not have permission to delete items", "danger")
        return redirect(url_for('item.listItems'))

    item= db.session.get(models.Item, itemID)
    if item.isDeleted:
        flash(f"Item already deleted", "warning")
        return redirect(url_for('item.listItems'))
    item.isDeleted = True
    db.session.commit()
    flash(f"Item deleted successfully!", "success")
    return redirect(url_for('item.listItems'))

@item_bp.route("/items/restore/<int:itemID>", methods=['GET'])
@login_required
def restoreItem(itemID):
   #forbid User roles from restoring
    if current_user.accessRole == AccessRoleEnum.User:
        flash(f"Access denied! You do not have permission to restore items", "danger")
        return redirect(url_for('item.listItems'))
    item= db.session.get(models.Item, itemID)
    if item.isDeleted:
        item.isDeleted = False
        db.session.commit()
        flash(f"Item restored successfully!", "success")
    return redirect(url_for('item.listItems'))

routes/mainRoutes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
import databases.models as models
from databases.models.user import AccessRoleEnum

#Blueprint to define the home page 
main_bp = Blueprint('main', __name__)

@main_bp.route("/", methods=['GET', 'POST'])
@login_required
def home():
    username= current_user.username
    user= models.User.query.filter_by(username=username).first()    
    return render_template("index.html", firstName=user.firstName,  AccessRoleEnum=AccessRoleEnum)

routes/vendorRoutes.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for
from flask_login import login_required, current_user
import databases.models as models
from databases.models.user import AccessRoleEnum
from databases.base import db
from forms import createVendorForm

#Blueprints to define all routes linking to vendor CRUD functions
vendor_bp = Blueprint('vendor', __name__)

@vendor_bp.route("/vendors")
@login_required
def listVendors():
    vendors = models.Vendor.query.filter_by(isDeleted=False)
    deletedVendors = models.Vendor.query.filter_by(isDeleted=True).all()
    return render_template('vendor.html', vendors=vendors, deletedVendors=deletedVendors, AccessRoleEnum=AccessRoleEnum)

@vendor_bp.route("/vendors/create", methods=['GET', 'POST'])
@login_required
def addVendor():
    form = createVendorForm()
    if form.validate_on_submit():
        try:
            formInput = models.Vendor(
                vendorName=form.vendorName.data,
                sustainabilityCertified=form.sustainabilityCertified.data
            )
            db.session.add(formInput)
            db.session.commit()
            flash(f"Vendor added successfully!", "success")
        except:
            db.session.rollback()
            flash(f"Something went wrong. Please try again.", "danger")
    return render_template("addVendor.html", form=form)

@vendor_bp.route("/vendors/update/<int:vendorID>", methods=['GET', 'POST'])
@login_required
def updateVendor(vendorID):
    vendor = db.session.get(models.Vendor, vendorID)
    if vendor.isDeleted:
         flash(f"Vendor is deleted", "warning")
         return redirect(url_for('vendor.listVendors'))
    form = createVendorForm(obj=vendor)
    if form.validate_on_submit():
        try:
            vendor.vendorName = form.vendorName.data
            vendor.sustainabilityCertified = form.sustainabilityCertified.data
            db.session.commit()
            flash(f"Vendor updated successfully!", "success")
        except:
            db.session.rollback()
            flash(f"Something went wrong. Please try again.", "danger")
    return render_template("addVendor.html", form=form)

@vendor_bp.route("/vendors/delete/<int:vendorID>", methods=['GET', 'POST'])
@login_required
def deleteVendor(vendorID):
    if current_user.accessRole == AccessRoleEnum.User:
        flash(f"Access denied! Access denied! You do not have permission to delete vendors", "danger")
        return redirect(url_for('vendor.listVendors'))
    vendor = db.session.get(models.Vendor, vendorID)
    if vendor.isDeleted:
         flash(f"Vendor already deleted", "warning")
         return redirect(url_for('vendor.listVendors'))
    vendor.isDeleted = True
    db.session.commit()
    flash(f"Vendor deleted successfully!", "success")
    return redirect(url_for('vendor.listVendors'))

@vendor_bp.route("/vendors/restore/<int:vendorID>", methods=['GET', 'POST'])
@login_required
def restoreVendor(vendorID):
    if current_user.accessRole == AccessRoleEnum.User:
        flash(f"Access denied! Access denied! You do not have permission to restore vendors", "danger")
        return redirect(url_for('vendor.listVendors'))
    vendor = db.session.get(models.Vendor, vendorID)
    if vendor.isDeleted:
        vendor.isDeleted = False
        db.session.commit()
        flash(f"Vendor restored successfully!", "success")
    return redirect(url_for('vendor.listVendors'))

templates/flashAlerts.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

templates/item.html
{% extends "base.html" %}
{% block content %}
{% include "standardNavigation.html" %}
{% include "flashAlerts.html" %}
<div class="container mt-4">
    <h1>Active Items</h1>
    <a href="{{ url_for('item.addItem')}}" class="btn btn-primary mb-3">Add a new item</a>
    <table class="table table-striped table-bordered">
      <thead class="table-light">
        <tr>
           <th>Item ID</th>
            <th>Vendor Name</th>
            <th>Username </th>
            <th>Item Category </th>
            <th>Expiry Date</th>
            <th>Status</th>
            <th>User Notes</th>
            <th>Action</th>
        </tr>
      </thead>
      <tbody>
      {% for item in items %}
        <tr>
          <td>{{ item.itemID}}</td>
          <td>{{item.vendorName}}</td>
          <td>{{item.username}}</td>
          <td>{{item.itemCategoryName}}</td>
          <td>{{item.expiryDate}}</td>
          <td>{{item.status}}</td>
          <td>{{item.userNotes}}</td>
          <td>
              <a href="{{ url_for('item.updateItem', itemID=item.itemID)}}?mode=edit&resource=item" class="btn btn-sm btn-secondary"> Edit </a>
              {% if current_user.accessRole == AccessRoleEnum.Admin %}
                  <button class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="setDeleteID('{{item.itemID}}')">Delete</button>
              {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
{% if current_user.accessRole == AccessRoleEnum.Admin %}
<div class="container mt-4">
<h1>Deleted Items</h1>
{% if deletedItems|length > 0 %}
  <table class="table table-striped table-bordered">
    <thead class="table-light">
      <tr>
        <th>Item ID</th>
        <th>Vendor Name</th>
        <th>Username </th>
        <th>Item Category </th>
        <th>Expiry Date</th>
        <th>Status</th>
        <th>User Notes</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for item in deletedItems %}
        <tr>
          <td>{{ item.itemID}}</td>
            <td>{{item.vendorName}}</td>
            <td>{{item.username}}</td>
            <td>{{item.itemCategoryName}}</td>
            <td>{{item.expiryDate}}</td>
            <td>{{item.status}}</td>
            <td>{{item.userNotes}}</td>
            <td>
              <a href="{{ url_for('item.restoreItem', itemID=item.itemID)}}" class="btn btn-sm btn-primary">Restore</a>
            </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    {% include "noneDeletedAlert.html" %}
  {% endif %}
</div>
{% endif %}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Item</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" id="itemToDelete">
        <p>Are you sure you want to delete item # : <strong id="itemIDPlaceholder"></strong>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="confirmDelete()">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
     function setDeleteID(itemID) {
        document.getElementById('itemToDelete').value = itemID;
        document.getElementById('itemIDPlaceholder').textContent = itemID;
    }
    function confirmDelete() {
        const itemID = document.getElementById('itemToDelete').value;
        window.location.href = "/items/delete/" + itemID;
    }
</script>
{% endblock %}

templates/itemCategory.html
{% extends "base.html" %}
{% block content %}
{% include "standardNavigation.html" %}
{% include "flashAlerts.html" %}
<div class="container mt-4">
  <h1>Active Item Categories</h1>
  <a href="{{ url_for('itemCategory.addItemCategory')}}" class="btn btn-primary mb-3">Add a new item Category</a>
  <table class="table table-striped table-bordered">
    <thead class="table-light">
      <tr>
        <th>Item Category ID</th>
        <th>Item Category</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    {% for itemCategory in itemCategories %}
      <tr>
        <td>{{itemCategory.itemCategoryID}} </td>
        <td>{{itemCategory.itemCategoryName}} </td>
        <td>
          <a href="{{ url_for('itemCategory.updateCategory', itemCategoryID=itemCategory.itemCategoryID)}}?mode=edit&resource=category"class="btn btn-sm btn-secondary"> Edit </a>
          {% if current_user.accessRole == AccessRoleEnum.Admin %} 
            <button class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="setDeleteID('{{itemCategory.itemCategoryID}}', '{{itemCategory.itemCategoryName}}')">Delete</button>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% if current_user.accessRole == AccessRoleEnum.Admin %}
  <div class="container mt-4">
    <h1>Deleted Item Categories</h1>
    {% if deletedCategories|length > 0 %}
      <table class="table table-striped table-bordered">
        <thead class="table-light">
          <tr>
            <th>Item Category ID</th>
            <th>Item Category</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for itemCategory in deletedCategories %}
            <tr>
              <td>{{itemCategory.itemCategoryID}} </td>
              <td>{{itemCategory.itemCategoryName}} </td>
              <td>
                <a href="{{ url_for('itemCategory.restoreCategory', itemCategoryID=itemCategory.itemCategoryID)}}" class="btn btn-sm btn-primary">Restore</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        {% include "noneDeletedAlert.html" %}
      {% endif %}
  </div>
{% endif %}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Item Category</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" id="itemCategoryToDelete">
        <p>Are you sure you want to delete <strong id="itemCategoryPlaceholder"></strong>? </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="confirmDelete()">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
     function setDeleteID(itemCategoryID, itemCategoryName) {
        document.getElementById('itemCategoryToDelete').value = itemCategoryID;
        document.getElementById('itemCategoryPlaceholder').textContent = itemCategoryName
    }
    function confirmDelete() {
        const itemCategoryID = document.getElementById('itemCategoryToDelete').value;
        window.location.href = "/categories/delete/" + itemCategoryID;
    }
</script>
{% endblock %}

templates/noneDeletedAlert.html
<div class="alert alert-info" role="alert">
     <p>Attention! There are no deleted records</p>
</div>

templates/vendor.html
{% extends "base.html" %}
{% block content %}
{% include "standardNavigation.html" %}
{% include "flashAlerts.html" %}
<div class="container mt-4">
  <h1>Active Vendors</h1>
  <a href="{{ url_for('vendor.addVendor')}}" class="btn btn-primary mb-3">Add a new vendor</a>
  <table class="table table-striped table-bordered">
    <thead class="table-light">
      <tr>
        <th>Vendor ID</th>
        <th>Vendor</th>
        <th>Sustainability Certified</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for vendor in vendors %}
        <tr>
          <td>{{vendor.vendorID}}</td>
          <td>{{vendor.vendorName}}</td>
          <td>{{vendor.sustainabilityCertified}}</td>
          <td>
            <a href="{{ url_for('vendor.updateVendor', vendorID=vendor.vendorID)}}?mode=edit&resource=vendor" class="btn btn-sm btn-secondary">Edit</a>
            {% if current_user.accessRole == AccessRoleEnum.Admin %}
            <button class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="setDeleteID('{{vendor.vendorID}}', '{{vendor.vendorName}}')">Delete</button>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% if current_user.accessRole == AccessRoleEnum.Admin %}
<div class="container mt-4">
  <h1>Deleted Vendors</h1>
  {% if deletedVendors|length > 0 %}
      <table class="table table-striped table-bordered">
        <thead class="table-light">
          <tr>
            <th>Vendor ID</th>
            <th>Vendor</th>
            <th>Sustainability Certified</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        {% for vendor in deletedVendors %}
          <tr>
            <td>{{vendor.vendorID}}</td>
            <td>{{vendor.vendorName}}</td>
            <td>{{vendor.sustainabilityCertified}}</td>
            <td>
              <a href="{{ url_for('vendor.restoreVendor', vendorID=vendor.vendorID)}}" class="btn btn-sm btn-primary">Restore</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    {% include "noneDeletedAlert.html" %}
   {% endif %}
</div>
{% endif %}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Vendor</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" id="vendorToDelete">
        <p>Are you sure you want to delete <strong id="vendorNamePlaceholder"></strong>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="confirmDelete()">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
  function setDeleteID(vendorID, vendorName) {
    document.getElementById('vendorToDelete').value = vendorID;
    document.getElementById('vendorNamePlaceholder').textContent = vendorName;
  }
  function confirmDelete() {
    const vendorID = document.getElementById('vendorToDelete').value;
    window.location.href = "/vendors/delete/" + vendorID;
  }
</script>
{% endblock %}